### PR TITLE
Added Results Page

### PR DESCRIPTION
**Pull request by nareshpoonia**
Added Results Page

### CODE REVIEW

**Review by stutisk — APPROVED** [review]
Code looks good to me ,just a suggestion you can give colors using variables !

**Review by Shivanshsharma01 — APPROVED** [review]
The code looks clean with good use of variables.

**Review by kjais1720 — APPROVED** [review]
Looks clean and readable with good use of utility classes👍

**Review by Radheshyam1234 — COMMENTED** [review]
code looks clean and good to merge

**Pull request merged**
